### ISSUE TITLE
Multiple models to be checked

### ISSUE THREAD

**Issue by thangkhungdien** [yuha0/applechecker#4]
Can we check multiple models on the command line in "model 1, model 2"?

**Comment by yuha0** [comment]
Haven't found out if Apple allows you to check more than one model in a single query. That means,  currently, checking multiple models would be just putting multiple `GET` calls in a `for` loop. So yes, it's possible. I just don't have a plan for that since it's almost the same as running multiple scripts and most people are just monitoring one or two items. 

Btw, It's not a very robust script so you may want to setup something like a cron job or upstart service that the script can restart after a crash. Then simply forget about how many scripts are running and just relax and wait for the email alerts. I personally like to run it as a `Docker` container.
