### ISSUE TITLE
applechecker does not check inventory available for iPhone Upgrade Program

### ISSUE THREAD

**Issue by ClarkGeek** [yuha0/applechecker#6]
Due to Apple allocating more inventory for the iPhone Upgrade Program (IUP) there is additional inventory that shows up for their stores using their reservation program.

https://reserve.cdn-apple.com/US/en_US/reserve/iPhone/availability?iPP=U

This may be a best done is a separate project but would you please be willing to setup a IUP reservation checker where you can specify the store locations and iPhone models you are interested in. Then of course it will alert you when it becomes available.

**Comment by ClarkGeek** [comment]
I also forgot to note that once a user has made a reservation that they do not have to purchase it through the iPhone Upgrade Program. They can choose to purchase it any way they want.

**Comment by yuha0** [comment]
@nephipower This script was meant to be generic because the endpoint it hits is generic (that endpoint can check any Apple Product with a model number). But the endpoint for IUP is for iPhone 7 only. 

Maybe it would be a better idea to write a different script to monitor the change of `https://reserve.cdn-apple.com/US/en_US/reserve/iPhone/availability.json`, which is a `store_code:availability_of_all_models` mapping. But to include this into my current script, there has to be an extra layer on top of it to differentiate iPhone 7 and other products by model number, but I don't have a plan for that.

**Comment by ClarkGeek** [comment]
@yuha0 Yes, I agree that it would be best to keep the original script generic. But it would be awesome to have a separate one to check the iPhone reservation site. The good thing about it too is that I think it would be reusable for future years.

I know last year they used this same site and it came in handy but i had to manually check it. However, being able to do automated checking at certain stores for certain models would be awesome.

Would you be willing to make a separate script for this use case?

**Comment by yuha0** [comment]
@nephipower Can't take that amount of time right now, and Apple should've already had enough in stock when I do. I will probably make one next year if I missed iPhone 7plus/8 launch day pre-order, haha.

**Comment by yuha0** [comment]
was planned to do this, but turned out this API was no longer available... :(
